options: &options
  allow_dynamic_fields: true # Configuration for whether or not to allow access to fields that do not have a field definition on the model. (default: true)
  identity_map_enabled: false # Enable the identity map, needed for eager loading. (default: false)
  include_root_in_json: false # Includes the root model name in json serialization. (default: false)
  include_type_for_serialization: false # Include the _type field in serializaion. (default: false)
  preload_models: false # Preload all models in development, needed when models use inheritance. (default: false)
  protect_sensitive_fields: true # Protect id and type from mass assignment. (default: true)
  raise_not_found_error: true # Raise an error when performing a #find and the document is not found. (default: true)
  scope_overwrite_exception: false # Raise an error when defining a scope with the same name as an existing method. (default: false)
  skip_version_check: false # Skip the database version check, used when connecting to a db without admin access. (default: false)
  use_activesupport_time_zone: false # User Active Support's time zone in conversions. (default: true)
  use_utc: true # Ensure all times are UTC in the app side. (default: false)


development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      database: wildcard_development
      hosts:
        - localhost:27017
	  options:
	    <<: *options


test:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
	  options:
	    <<: *options


production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
	  options:
	    <<: *options

